# The Docker image that will be used to build your app
image: busybox

create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  before_script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - rm -rf public
  script:
    - mkdir public
    - cp -r index.html css js assets public/
    # Inject values directly into HTML
    - sed -i "s/data-emailjs-user-id=\"[^\"]*\"/data-emailjs-user-id=\"$EMAILJS_USER_ID\"/g" public/index.html
    - sed -i "s/data-turnstile-site-key=\"[^\"]*\"/data-turnstile-site-key=\"$TURNSTILE_SITE_KEY\"/g" public/index.html
    - sed -i "s|data-stripe-url=\"[^\"]*\"|data-stripe-url=\"$STRIPE_PLENO_DERECHO\"|g" public/index.html
    - sed -i "s|data-stripe-url=\"[^\"]*\"|data-stripe-url=\"$STRIPE_ESTUDIANTE\"|g" public/index.html
    - sed -i "s|data-stripe-url=\"[^\"]*\"|data-stripe-url=\"$STRIPE_COLABORADOR\"|g" public/index.html
