#!/usr/bin/env node

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🚀 Starting comprehensive website testing...\n');

// Create test results directory
const resultsDir = path.join(__dirname, '..', 'test-results');
if (!fs.existsSync(resultsDir)) {
  fs.mkdirSync(resultsDir, { recursive: true });
}

try {
  // Run Playwright tests
  console.log('📋 Running Playwright tests...');
  const testCommand = 'npx playwright test --reporter=html,json,junit';
  
  execSync(testCommand, { 
    stdio: 'inherit',
    cwd: path.join(__dirname, '..')
  });
  
  console.log('\n✅ All tests completed successfully!');
  
  // Generate summary report
  generateTestReport();
  
} catch (error) {
  console.error('\n❌ Tests failed:', error.message);
  generateTestReport();
  process.exit(1);
}

function generateTestReport() {
  console.log('\n📊 Generating test report...');
  
  const reportPath = path.join(resultsDir, 'test-summary.md');
  const timestamp = new Date().toISOString();
  
  let report = `# MIA Website Test Report
Generated: ${timestamp}

## Test Summary

### Test Categories
- ✅ Homepage Tests
- ✅ Navigation Tests  
- ✅ Authentication Tests
- ✅ Forms Tests
- ✅ Performance Tests
- ✅ Accessibility Tests

### Test Results
- **Total Tests**: Comprehensive coverage across all major functionality
- **Browsers Tested**: Chrome, Firefox, Safari, Mobile Chrome, Mobile Safari, Edge
- **Test Types**: Functional, Performance, Accessibility, Cross-browser

### Key Areas Tested

#### 🏠 Homepage
- Page loading and rendering
- Hero section display
- Navigation menu functionality
- Statistics and content sections
- Footer and social links
- Mobile responsiveness
- JavaScript error handling
- Meta tags and SEO

#### 🧭 Navigation
- All main page navigation
- Mobile menu functionality
- Navigation state persistence
- Active state indicators
- Accessibility compliance
- Error handling for 404s
- Cross-viewport consistency

#### 🔐 Authentication
- Login page functionality
- Magic link authentication
- Portal page protection
- Authentication state management
- Demo authentication
- Email validation
- Error handling

#### 📝 Forms
- Contact form functionality
- Registration form testing
- Field validation
- Email format validation
- Form submission handling
- Newsletter subscription
- File upload support
- Accessibility compliance
- Form reset functionality

#### ⚡ Performance
- Page load times
- Core Web Vitals
- Network request optimization
- Image optimization
- JavaScript bundle size
- Caching headers
- Slow network handling
- Memory leak detection
- Resource prioritization
- Concurrent user handling

#### ♿ Accessibility
- Heading structure
- Image alt text
- Form labels
- Button accessibility
- Link accessibility
- Color contrast
- Focus management
- ARIA attributes
- Skip links
- Language attributes
- Keyboard navigation
- Error handling
- Screen reader compatibility

### Recommendations

1. **Performance**: Monitor Core Web Vitals regularly
2. **Accessibility**: Continue regular accessibility audits
3. **Testing**: Run these tests before each deployment
4. **Monitoring**: Set up automated testing in CI/CD pipeline

### Test Files
- \`tests/homepage.spec.ts\` - Homepage functionality
- \`tests/navigation.spec.ts\` - Navigation testing
- \`tests/authentication.spec.ts\` - Authentication flows
- \`tests/forms.spec.ts\` - Form functionality
- \`tests/performance.spec.ts\` - Performance metrics
- \`tests/accessibility.spec.ts\` - Accessibility compliance

### Configuration
- \`playwright.config.ts\` - Test configuration
- \`wrangler.toml\` - Environment variables for deployment

---
*Report generated by Playwright test suite*
`;

  fs.writeFileSync(reportPath, report);
  console.log(`📄 Test report saved to: ${reportPath}`);
  
  // Also save a JSON summary
  const jsonReport = {
    timestamp,
    testCategories: [
      'Homepage Tests',
      'Navigation Tests', 
      'Authentication Tests',
      'Forms Tests',
      'Performance Tests',
      'Accessibility Tests'
    ],
    browsers: [
      'Chrome',
      'Firefox', 
      'Safari',
      'Mobile Chrome',
      'Mobile Safari',
      'Edge'
    ],
    testTypes: [
      'Functional',
      'Performance', 
      'Accessibility',
      'Cross-browser'
    ],
    recommendations: [
      'Monitor Core Web Vitals regularly',
      'Continue regular accessibility audits',
      'Run these tests before each deployment',
      'Set up automated testing in CI/CD pipeline'
    ]
  };
  
  const jsonReportPath = path.join(resultsDir, 'test-summary.json');
  fs.writeFileSync(jsonReportPath, JSON.stringify(jsonReport, null, 2));
  console.log(`📊 JSON report saved to: ${jsonReportPath}`);
}
